CREATE TABLE BOOK 
(
    ISBN    CHAR(13)    NOT NULL, 
    Title   VARCHAR(15)     NOT NULL,
    Summary VARCHAR(100)    NOT NULL, 
    Language VARCHAR(15)    NOT NULL,
    Price   INT     NOT NULL,
    Is_borrowed   BOOLEAN    NOT NULL,
    Page    INT     NOT NULL,
    Library VARCHAR(15) NOT NULL,
    Floor  INT     NOT NULL,
    Shelf_number INT NOT NULL,
    Author_ID VARCHAR(15) NOT NULL,
    Genre_ID VARCHAR(15) NOT NULL,
    Publisher_ID VARCHAR(15) NOT NULL,
    PRIMARY KEY (ISBN)
);

CREATE TABLE ACCOUNT
(
    ID      VARCHAR(15)     NOT NULL,
    Password    VARCHAR(15)     NOT NULL,
    Name    VARCHAR(15)     NOT NULL,
    Email   VARCHAR(30)     NOT NULL,
    Phone   VARCHAR(15),
    PRIMARY KEY (ID) 
);

CREATE TABLE RATING
(
	Rating_index INT NOT NULL,
    Rating  INT     NOT NULL,
    Review VARCHAR(100),
    Book_ID char(13) NOT NULL,
    Account_ID VARCHAR(15) NOT NULL,
    PRIMARY KEY (Rating_index),
    FOREIGN KEY (Book_ID) REFERENCES BOOK (ISBN) ON DELETE CASCADE,
    FOREIGN KEY (Account_ID) REFERENCES Account (ID) ON DELETE CASCADE
);

CREATE TABLE ADMIN
(
    ID      VARCHAR(15)     NOT NULL,
    Password    VARCHAR(15)     NOT NULL,
    Name    VARCHAR(15)     NOT NULL,
    Email   VARCHAR(30)     NOT NULL,
    Phone   VARCHAR(15),
    PRIMARY KEY (ID)
);

CREATE TABLE GENRE
(
    ID    VARCHAR(15)     NOT NULL,
    Genres  VARCHAR(15),
    PRIMARY KEY (ID)
);

CREATE TABLE PUBLISHER
(
    ID  VARCHAR(15)     NOT NULL,
    Name    VARCHAR(15)     NOT NULL,
    Address     VARCHAR(30)     NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TRANSLATOR
(
    ID  VARCHAR(15)     NOT NULL,
    Name    VARCHAR(15)     NOT NULL,
    Language     VARCHAR(15)     NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE AUTHOR
(
    ID   VARCHAR(15)     NOT NULL,
    Name    VARCHAR(15)     NOT NULL,
    Brith_year  DATE    NOT NULL,
    Death_year  DATE,
    Nationality VARCHAR(15)     NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE BOOK ADD FOREIGN KEY (Author_ID) REFERENCES AUTHOR(ID);
ALTER TABLE BOOK ADD FOREIGN KEY (Genre_ID) REFERENCES GENRE(ID);
ALTER TABLE BOOK ADD FOREIGN KEY (Publisher_ID) REFERENCES PUBLISHER(ID);

CREATE TABLE BORROW
(
    Borrow_date DATE    NOT NULL,
    Return_date DATE    NOT NULL,
    Account_ID VARCHAR(15) NOT NULL,
    Book_ID CHAR(13) NOT NULL, 
    FOREIGN KEY (Account_ID) REFERENCES ACCOUNT(ID),
    FOREIGN KEY (Book_ID) REFERENCES BOOK (ISBN)
);

CREATE TABLE BELONG
(
    Genre_ID VARCHAR(15) NOT NULL,
    Book_ID CHAR(13) NOT NULL,
    FOREIGN KEY (Genre_ID) REFERENCES GENRE(ID),
    FOREIGN KEY (Book_ID) REFERENCES BOOK (ISBN)
);

CREATE TABLE MANAGES
(
    Admin_ID VARCHAR(15) NOT NULL,
    Book_ID CHAR(13) NOT NULL,
    FOREIGN KEY (Admin_ID) REFERENCES ADMIN(ID),
    FOREIGN KEY (Book_ID) REFERENCES BOOK (ISBN)
);

CREATE TABLE PUBLISHED_BY
(
    Pub_ID VARCHAR(15) NOT NULL,
    Book_ID CHAR(13) NOT NULL,
    FOREIGN KEY (Pub_ID) REFERENCES PUBLISHER(ID),
    FOREIGN KEY (Book_ID) REFERENCES BOOK (ISBN)
);

CREATE TABLE TRANSLATED
(
    Translator_ID VARCHAR(15) NOT NULL,
    Book_ID CHAR(13) NOT NULL,
    FOREIGN KEY (Translator_ID) REFERENCES TRANSLATOR(ID),
    FOREIGN KEY (Book_ID) REFERENCES BOOK (ISBN)
);

CREATE TABLE AUTHORED
(
    Author_ID VARCHAR(15) NOT NULL,
    Book_ID CHAR(13) NOT NULL,
    FOREIGN KEY (Author_ID) REFERENCES AUTHOR(ID) ON DELETE CASCADE,
    FOREIGN KEY (Book_ID) REFERENCES BOOK (ISBN)
);

DESC BOOK;
DESC RATING;
DESC ACCOUNT;
DESC ADMIN;
DESC GENRE;
DESC PUBLISHER;
DESC TRANSLATOR; 
DESC AUTHOR;
DESC BORROW;
DESC BELONG;
DESC MANAGES;
DESC PUBLISHED_BY;
DESC TRANSLATED;
DESC AUTHORED;

DROP TABLE BOOK;
DROP TABLE RATING;
DROP TABLE ACCOUNT;
DROP TABLE ADMIN; 
DROP TABLE GENRE;
DROP TABLE PUBLISHER;
DROP TABLE TRANSLATOR;
DROP TABLE AUTHOR;
DROP TABLE BORROW;
DROP TABLE BELONG;
DROP TABLE MANAGES;
DROP TABLE PUBLISHED_BY;
DROP TABLE TRANSLATED;
DROP TABLE AUTHORED;
