CREATE TABLE BOOK 
(
    ISBN    CHAR(13)    NOT NULL, 
    Title   VARCHAR(15)     NOT NULL,
    Summary VARCHAR(100)    NOT NULL, 
    Language VARCHAR(15)    NOT NULL,
    Price   INT     NOT NULL,
    State   INT    NOT NULL,
    Page    INT     NOT NULL,
    PRIMARY KEY (ISBN)
);
CREATE TABLE LOCATION
(
    Location_index INT NOT NULL,
	Library VARCHAR(15) NOT NULL,
    Floor  INT     NOT NULL,
    Shelf_number INT NOT NULL,
    PRIMARY KEY (Location_index)
);

CREATE TABLE RATING
(
	Rating_index INT NOT NULL,
    Rating  INT     NOT NULL,
    Review VARCHAR(100),
    PRIMARY KEY (Rating_index),
    FOREIGN KEY (Book_ID) REFERENCES BOOK (ISBN);
    FOREIGN KEY (Account_ID) REFERENCES Account (ID);
);
CREATE TABLE ACCOUNT
(
    ID      VARCHAR(15)     NOT NULL,
    Password    VARCHAR(15)     NOT NULL,
    Name    VARCHAR(15)     NOT NULL,
    Email   VARCHAR(30)     NOT NULL,
    Phone   VARCHAR(15),
    PRIMARY KEY (Account_ID) 
);
CREATE TABLE ADMIN
(
    ID      VARCHAR(15)     NOT NULL,
    Password    VARCHAR(15)     NOT NULL,
    Name    VARCHAR(15)     NOT NULL,
    Email   VARCHAR(30)     NOT NULL,
    Phone   VARCHAR(15),
    PRIMARY KEY (Admin_ID)
);
CREATE TABLE GENRE
(
    ID    VARCHAR(15)     NOT NULL,
    Genres  VARCHAR(15),
    PRIMARY KEY (Genre_ID)
);
CREATE TABLE PUBLISHER
(
    ID  VARCHAR(15)     NOT NULL,
    Name    VARCHAR(15)     NOT NULL,
    Address     VARCHAR(30)     NOT NULL,
    PRIMARY KEY (Pub_ID)
);
CREATE TABLE TRANSLATOR
(
    ID  VARCHAR(15)     NOT NULL,
    Name    VARCHAR(15)     NOT NULL,
    Language     VARCHAR(15)     NOT NULL,
    PRIMARY KEY (Translator_ID)
);
CREATE TABLE AUTHOR
(
    ID   VARCHAR(15)     NOT NULL,
    Name    VARCHAR(15)     NOT NULL,
    Brith_year  DATE    NOT NULL,
    Death_year  DATE,
    Nationality VARCHAR(15)     NOT NULL,
    PRIMARY KEY (Author_ID)
);
CREATE TABLE BORROW
(
    Borrow_date DATE    NOT NULL,
    Return_date DATE    NOT NULL,
    FOREIGN KEY (Account_ID) REFERENCES ACCOUNT(ID);
    FOREIGN KEY (Book_ID) REFERENCES BOOK (ISBN);
);
CREATE TABLE BELONG
(
    FOREIGN KEY (Genre_ID) REFERENCES GENRE(ID);
    FOREIGN KEY (Book_ID) REFERENCES BOOK (ISBN);
);
CREATE TABLE MANAGES
(
    FOREIGN KEY (Admin_ID) REFERENCES ADMIN(ID);
    FOREIGN KEY (Book_ID) REFERENCES BOOK (ISBN);
);
CREATE TABLE PUBLISHED_BY
(
    FOREIGN KEY (Pub_ID) REFERENCES PUBLISHER(ID);
    FOREIGN KEY (Book_ID) REFERENCES BOOK (ISBN);
);
CREATE TABLE TRANSLATED
(
    FOREIGN KEY (Translator_ID) REFERENCES TRANSLATOR(ID);
    FOREIGN KEY (Book_ID) REFERENCES BOOK (ISBN);
);
CREATE TABLE AUTHORED
(
    FOREIGN KEY (Author_ID) REFERENCES AUTHOR(ID);
    FOREIGN KEY (Book_ID) REFERENCES BOOK (ISBN);
);

DESC BOOK;
DESC LOCATION;
DESC RATING;
DESC ACCOUNT;
DESC ADMIN;
DESC GENRE;
DESC PUBLISHER;
DESC TRANSLATOR; 
DESC AUTHOR;
DESC BORROW;
DESC BELONG;
DESC MANAGES;
DESC PUBLISHED_BY;
DESC TRANSLATED;
DESC AUTHORED;